name: "Pull code from public PR"

inputs:
  Repository-name:
    description: 'Repository name'
    required: true
  PR-number:
    description: 'Pull request number'
    required: true
  Repo-PAT:
    description: 'INNERSOURCE repo token'
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout Code
    uses: actions/checkout@v4
    with:
      ref: main
      path: internal_repo

  - name: Fetch code from public PR
    run: |
      cd internal_repo
      git remote add opea_rag https://github.com/${{ inputs.Repository-name }}
      git fetch opea_rag
      git checkout public_PR_${{ inputs.PR-number }} || git checkout -b public_PR_${{ inputs.PR-number }}
      git fetch opea_rag pull/${{ inputs.PR-number }}/head:external_pr_${{ inputs.PR-number }}
    shell: bash

  - name: Verify git diff
    run: |
      cd internal_repo
      if git diff --quiet external_pr_${{ inputs.PR-number }}^..external_pr_${{ inputs.PR-number }} -- .github; then
        echo "No changes in .github directory."
      else
        echo "Changes detected in .github directory."
        exit 1
      fi
    shell: bash

  - name: Cherry pick code from public PR
    run: |
      cd internal_repo
      git config user.email "actions@github.com"
      git config user.name "Github Actions"
      git checkout public_PR_${{ inputs.PR-number }}
      git cherry-pick external_pr_${{ inputs.PR-number }}^..external_pr_${{ inputs.PR-number }} -X theirs
      git push --set-upstream origin public_PR_${{ inputs.PR-number }}
    shell: bash

  - name: Install sudo
    run: apt update && apt -y install sudo
    shell: bash

  - name: Install Github CLI
    run: |
      (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
      && sudo mkdir -p -m 755 /etc/apt/keyrings \
      && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
      && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
      && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
      && sudo apt update \
      && sudo apt install gh -y
    shell: bash

  - name: Create PR
    run: |
      gh pr create \
      --base main \
      --head public_PR_${{ inputs.PR-number }} \
      --title 'Public PR No. ${{ inputs.PR-number }}' \
      --body 'PR No. ${{ inputs.PR-number }} from https://github.com/${{ inputs.Repository-name }}/pull/${{ inputs.PR-number }} \
      :warning: **Do not merge until public PR is merged!**' \
      || echo "PR already exists"
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.Repo-PAT }}
