{{- if index .Values "mssql" "enabled" }} 
{{- if index .Values "mssql" "persistence" "enabled" -}}
# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mssql.persistence.size | default "10Gi" | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-log
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
{{- end -}}
{{- end -}}
