name: "Push code to public main"

inputs:
  OPEA_PAT:
    description: 'OPEA repo token'
    required: true

runs:
  using: "composite"
  steps:
  - name: Fetch external repo
    uses: actions/checkout@v4
    with:
      repository: 'opea-project/Enterprise-RAG'
      ref: 'main'
      token: ${{ inputs.OPEA_PAT }}
      path: public_repo

  - name: Fetch internal repo
    uses: actions/checkout@v4
    with:
      ref: 'main'
      path: internal_repo
      fetch-depth: 0

  - name: Merge code from internal main
    id: push
    run: |
      cd public_repo
      git config --global user.email "actions@github.com"
      git config --global user.name "Github Actions"
      git remote add opea_rag https://github.com/opea-project/Enterprise-RAG
      git remote add internal_rag ../internal_repo
      git fetch internal_rag
      git checkout internal_main || git checkout -b internal_main
      git merge internal_rag/main --no-commit --allow-unrelated-histories --strategy-option=theirs --squash
      git reset -- .github
      if [ -d ".github" ]; then
        cd .github
        git clean -fd
        cd ..
      fi
      git checkout -- .
      if [ -n "$(git status --porcelain)" ]; then
        echo "push=true" >> "$GITHUB_OUTPUT"
        git add --all && git commit -m "Merge code from internal to public main" --signoff
        git push --set-upstream opea_rag internal_main
      else
        echo "No changes to be commited";
      fi
    shell: bash

  - name: Install sudo
    run: apt update && apt -y install sudo
    shell: bash

  - name: Install Github CLI
    run: |
      (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
      && sudo mkdir -p -m 755 /etc/apt/keyrings \
      && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
      && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
      && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
      && sudo apt update \
      && sudo apt install gh -y
    shell: bash

  - name: Create PR
    if: ${{ steps.push.outputs.push == 'true' }}
    run: |
      cd public_repo
      gh pr create --base main --head internal_main --title 'Internal main' --body 'Internal main changes' || echo "PR already exists"
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.OPEA_PAT }}

  - name: Verify git diff
    run: |
      cd public_repo
      echo "git diff with .github/ excluded:"
      git diff internal_rag/main --name-only -- ":(exclude).github/*"
      if [[ -z "$(git diff internal_rag/main --name-only -- ":(exclude).github/*")" ]]; then
        exit 0;
      fi
    shell: bash
