name: Coverity Scans JS

on:
  pull_request:
    branches: [ main ]

jobs:
  coverity-scan-javascript:
    name: Coverity scans Javascript
    runs-on: [innersource.prod.amr.dind]
    container: cache-registry.caas.intel.com/cache/library/python:3.11
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Coverity scan for Javascript
      uses: ./.github/actions/coverity-scan
      with:
        ANALYZE_OPTIONS: --enable-audit-mode --webapp-security --enable-default --checker-option DOM_XSS:distrust_all:true
        COMPILER_TYPE: javascript
        RAG_COVERITY_USER: ${{ secrets.RAG_COVERITY_USER }}
        RAG_COVERITY_PASSWORD: ${{ secrets.RAG_COVERITY_PASSWORD }}
