name: "SDL"

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.txt"

  release:
    types:
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PR-number: ${{ github.event_name == 'release' && '' || github.event.number }}

jobs:
  idf:
    name: IDF Pack
    runs-on: [innersource.prod.amr.dind]
    defaults:
      run:
        shell: bash
    container: cache-registry.caas.intel.com/cache/library/python:3.11
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SDL scan
      uses: ./.github/actions/sdl-scan
      with:
        Repository-name: ${{ github.repository }}
        PR-number: ${{ env.PR-number }}
        user: ${{ vars.FACELESS_USER }}
        pass: ${{ secrets.FACELESS_PASS }}

  bandit:
    name: Bandit
    runs-on: [innersource.prod.amr.dind]
    container: cache-registry.caas.intel.com/cache/library/python:slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit
        # At that time latest release were using old upload-artifact v3 which was blocked by GH
        uses: intel-innersource/frameworks.actions.bandit@e52968db652a1f1ed32dad6085a5b9350147af28
