name: "Trivy Scan of PR (deprecated)"

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true

jobs:
  Trivy-scan:
    if: ${{ github.repository == 'intel-innersource/applications.ai.enterprise-rag.enterprise-ai-solution' }}
    runs-on: [innersource.prod.amr.dind]
    name: Trivy Scan
    container:
      image: cache-registry.caas.intel.com/cache/library/python:3.11
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
            ref: refs/pull/${{ github.event.inputs.PR_number }}/head

      - name: Trivy scan
        uses: ./.github/actions/trivy-scan-pr
        with:
          PR-number: ${{ github.event.inputs.PR_number }}

      - name: Warn about deprecation
        run: |
          echo "### ⚠️ Job deprecated! ⚠️ \n" >> $GITHUB_STEP_SUMMARY
          echo "This job seems unused for long time. It's about to become deleted. If you think we should keep it, contact Kurzacz, Kamil <kamil.kurzacz@intel.com>" >> $GITHUB_STEP_SUMMARY
