name: Images security scans
run-name: Sec scan reg '${{ github.event.inputs.REGISTRY || 'pre' }}' tag '${{ github.event.inputs.TAG || 'latest' }}'
on:
  workflow_dispatch:
    inputs:
      REGISTRY:
        description: Select image registry
        required: true
        type: choice
        options:
          - prod
          - pre
      TAG:
        description: Tag of images
        required: true

  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC

jobs:
  scan:
    name: "Scan image - ${{ matrix.image-name }}"
    runs-on: [ innersource.prod.amr.dind-xl ]
    container:
      image: aquasec/trivy
      options: --entrypoint ""
    strategy:
      fail-fast: false
      matrix:
        image-name:
          - embedding
          - mosec_embedding
          - ovms_embedding
          - torchserve_embedding
          - llm
          - gmcmanager
          - gmcrouter
          - chatqna-conversation-ui
          - language-detection
          - otelcol-contrib-journalctl
          - vllm-gaudi
          - system-fingerprint
          - dpguard
          - in-guard
          - out-guard
          - enhanced-dataprep
          - prompt_template
          - retriever
          - ingestion
          - reranking
          - torchserve_reranking
          - hierarchical_dataprep
          - text-compression
          - text-extractor
          - text-splitter
    env:
      IMAGE_NAME_PREFIX: "erag-"
      # Set default values for REGISTRY and TAG for weekly scans
      # On manual scans, values from inputs are used
      REGISTRY: ${{ github.event.inputs.REGISTRY || 'pre' }}
      TAG: ${{ github.event.inputs.TAG || 'latest' }}
      HARBOR_PROD_URL: "ger-is-registry.caas.intel.com/intel-ai"
      HARBOR_PRE_URL: "ger-is-registry-pre.caas.intel.com/intel-ai-for-enterprise-rag/erag"
      TRIVY_DISABLE_VEX_NOTICE: true
      ERROR_RC: 1   # Error means test did not even finish
      FAIL_RC: 2    # Fail means scan was done correctly, but found issues

    steps:
      - name: Set registry url
        run: |
          if [[ "${{ env.REGISTRY }}" == "prod" ]]; then
            echo "REGISTRY_URL=${{ env.HARBOR_PROD_URL }}" >> $GITHUB_ENV
          else
            echo "REGISTRY_URL=${{ env.HARBOR_PRE_URL }}" >> $GITHUB_ENV
          fi

      - name: Set credentials
        run: |
          if [[ "${{ env.REGISTRY }}" == "prod" ]]; then
            echo "REG_USERNAME=${{ vars.HARBOR_PROD_USER }}" >> $GITHUB_ENV
            echo "REG_PASSWORD=${{ secrets.HARBOR_PROD_PASS }}" >> $GITHUB_ENV
          else
            echo "REG_USERNAME=${{ vars.HARBOR_PRE_USER }}" >> $GITHUB_ENV
            echo "REG_PASSWORD=${{ secrets.HARBOR_PRE_PASS }}" >> $GITHUB_ENV
          fi

      - name: Install minor dependencies
        run: apk add curl openssl

      - name: Download certificates
        run: |
          curl http://pki.intel.com/crt/IntelSHA256RootCA.crt > /tmp/IntelSHA256RootCA.crt  &&
          curl http://certificates.intel.com/repository/certificates/Intel%20Root%20CA.crt > /tmp/IntelRootCA.crt  &&
          openssl x509 -inform der -in /tmp/IntelSHA256RootCA.crt -outform pem -out /usr/local/share/ca-certificates/IntelSHA256RootCA-base64.crt  &&
          openssl x509 -inform der -in /tmp/IntelRootCA.crt -outform pem -out /usr/local/share/ca-certificates/IntelRootCA-base64.crt  &&
          update-ca-certificates

      - name: Download Trivy DB
        run: trivy image --download-db-only

      - name: Create artifacts dir
        run: mkdir -p results

      - name: Install Python
        run: |
          apk update
          apk add --no-cache python3~3.12
          ln -sf /usr/bin/python3 /usr/bin/python
          apk add --no-cache py3-pip
          python --version

      - name: Install and configure skopeo
        run: |
          apk add docker-cli skopeo
          echo '${{ env.REG_PASSWORD }}' | skopeo login --username '${{ env.REG_USERNAME }}' --password-stdin ${{ env.REGISTRY_URL }}

      - name: Create full image URI
        run: |
          uri="${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME_PREFIX }}${{ matrix.image-name }}:${{ env.TAG }}"
          echo "full_image_uri=$uri" >> $GITHUB_ENV
          echo "::debug::full_image_uri is set to $uri"

      # CaaS registry often hangs, therefore more robust approach required.
      - name: Pull the image
        id: skopeo-pull
        run: |
          MAX_RETRIES=5
          TIMEOUT=600  # 10 minutes in seconds
          COUNT=0
          SUCCESS=0

          while [ $COUNT -lt $MAX_RETRIES ]; do
            echo "Attempt $((COUNT+1)) / $MAX_RETRIES..."
            timeout $TIMEOUT skopeo copy docker://${{ env.full_image_uri }} oci:/image && SUCCESS=1 && break
            COUNT=$((COUNT+1))
            echo "Attempt $COUNT failed. Retrying..."
          done

          if [ $SUCCESS -ne 1 ]; then
            echo "All $MAX_RETRIES attempts failed. Exiting with error."
            exit 1
          else
            echo "Skopeo copy succeeded."
          fi

      - name: Run the full scan
        id: trivy-full
        run: |
          # When trivy fails, bash will exit immeadiately.
          # Thus, command to collect exit code normal way is pointless. See more:
          # https://github.com/orgs/community/discussions/46992

          trap 'echo "exit-code=$?" >> "$GITHUB_OUTPUT"' EXIT

          trivy image -q \
            --input /image \
            --scanners vuln \
            --exit-code ${{ env.FAIL_RC }} \
            --timeout 40m \
            --skip-dirs "/compliance" \
            --format table \
            ${{ env.full_image_uri }}
        continue-on-error: true

      - name: Rerun the full scan in debug
        if: ${{ steps.trivy-full.outputs.exit-code == env.ERROR_RC }}
        run: |
          echo "::error::Trivy scan had errors when running"
          trivy image -d \
            --input /image \
            --scanners vuln \
            --timeout 40m \
            --ignore-unfixed \
            --skip-dirs "/compliance" \
            --format table \
            ${{ env.full_image_uri }} \
            | tee trivy-report.txt
          exit ${{ env.ERROR_RC }}

      - name: Checkout (necessary) code
        uses: actions/checkout@v4
        with:
          path: repo
          sparse-checkout: .github/trivy
          sparse-checkout-cone-mode: false

      - name: Run the scan for Github Summaries
        id: trivy-json
        if: ${{ steps.trivy-full.outputs.exit-code != env.ERROR_RC }}
        run: |
          trap 'echo "exit-code=$?" >> "$GITHUB_OUTPUT"' EXIT
          trivy image \
            --input /image \
            --scanners vuln \
            --timeout 40m \
            --skip-dirs "/compliance" \
            --format json \
            --output results/trivy-raw.json \
            ${{ env.full_image_uri }}
          echo "exit-code=$?" >> $GITHUB_OUTPUT

      - name: Run the scan for SDL report
        id: trivy-sdl
        if: ${{ steps.trivy-full.outputs.exit-code != env.ERROR_RC }}
        run: |
          trap 'echo "exit-code=$?" >> "$GITHUB_OUTPUT"' EXIT
          trivy image \
            --input /image \
            --config repo/.github/trivy/sdl-config.yaml \
            --ignore-unfixed \
            ${{ env.full_image_uri }}
          echo "exit-code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Move SDL report
        if: ${{ steps.trivy-sdl.outputs.exit-code != env.ERROR_RC }}
        run: mv sdl-scan-results.csv results/sdl-scan-results.csv

      - name: Trivy general feedback
        if: always()
        run: |
          FULL_RC=${{ steps.trivy-full.outputs.exit-code }}
          SDL_RC=${{ steps.trivy-sdl.outputs.exit-code }}

          if [ "$FULL_RC" -eq ${{ env.ERROR_RC }} ] || [ "$SDL_RC" -eq ${{ env.ERROR_RC }} ]; then
            echo ":exclamation: Full or SDL Trivy scan faced errors" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "$SDL_RC" -eq 0 ]; then
            echo ":white_check_mark: Scan positive" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "$SDL_RC" -eq ${{ env.FAIL_RC }} ]; then
            echo ":x: Scan negative" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Postprocess Trivy JSON
        if: ${{ steps.trivy-json.outcome == 'success' }}
        run: |
          python repo/.github/trivy/json_postprocess.py results/trivy-raw.json results/trivy-postprocessed.json

      - name: Run summary script
        if: ${{ steps.trivy-json.outcome == 'success' }}
        run: |
          python repo/.github/trivy/summary_builder_one_image.py results/trivy-postprocessed.json >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports-${{ matrix.image-name }}
          path: results/*

      - name: Fail workflow if the Trivy SDL scan failed
        if: ${{ steps.trivy-sdl.outcome == 'failure' }}
        run: |
          echo "::error::Trivy SDL scan did not finish successfully"
          exit 1

  summary:
    name: "Summarization"
    needs: scan
    runs-on: innersource.prod.amr.dind
    if: always()
    container: cache-registry.caas.intel.com/cache/library/python:3.11
    defaults:
      run:
        shell: bash
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./results

      - name: List downloaded files
        run: ls -R ./results

      - name: Checkout (necessary) code
        uses: actions/checkout@v4
        with:
          path: repo
          sparse-checkout: .github/trivy
          sparse-checkout-cone-mode: false

      - name: Run summary script
        run: |
          python repo/.github/trivy/summary_builder_all.py results results/summary-all.csv

      - name: Upload final archive
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-archive
          path: ./results
